SPAM/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('web.urls')),
    path('web/', include('web.urls')),
]

web/urls.py
from django.urls import path

from . import views

app_name = 'web'

urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'index/', views.index, name='index'),
    path('huizong', views.huizong, name='huizong'),
    path('yuce', views.yuce, name='yuce'),
]

web/models.py
from django.db import models
import os

os.environ['DJANGO_SETTINGS_MODULE'] = 'SPAM.settings'

# Create your models here.

class Dataset(models.Model):
    id=models.IntegerField(verbose_name='主键',primary_key=True)
    youjian = models.TextField(verbose_name='短信内容',default='')
    lable = models.IntegerField(verbose_name='分类标签', default=0)

    def __str__(self):
        return self.youjian

    class Meta:
        verbose_name = u"数据集"
        verbose_name_plural = verbose_name




class Stopword(models.Model):

    name = models.CharField(verbose_name='停用词',default='',max_length=255)
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = u"停用词表"
        verbose_name_plural = verbose_name

web/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from recognition import rec
from . import models


@login_required
def index(request):
    if request.method == 'GET':
        results = models.Dataset.objects.all()[:1000]
        Search = request.GET.get('Search', '')
        if Search:
            results = models.Dataset.objects.raw('select * from dataset where youjian= ' + Search)
            models.Dataset.objects.filter(youjian__icontains=Search)
        return render(request, 'SPAM/table.html', locals())


@login_required
def huizong(request):
    if request.method == 'GET':
        return render(request, 'SPAM/huizong.html', locals())
    elif request.method == 'POST':
        Search = request.POST.get('Search', '')
        predict = rec(Search)
        if predict == "0":
            result = '非垃圾短信'
        elif predict == "1":
            result = '垃圾短信'
        return render(request, 'SPAM/huizong.html', locals())


@login_required
def yuce(request):
    datas1 = models.Dataset.objects.filter(lable=0).count()
    datas2 = models.Dataset.objects.filter(lable=1).count()
    print(datas1, datas2)
    dict_value = [{"name": '垃圾短信', "value": datas1}, {"name": '非垃圾短信', "value": datas2}]
    return render(request, 'SPAM/yuce.html', locals())

web/templates/SPAM/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
    <meta name="author" content="GeeksLabs">
    <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
    <link rel="shortcut icon" href="/static/img/favicon.png">

    <title>{% block title %}主页{% endblock %}</title>

<!--        <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/echarts@5/dist/echarts.min.js"></script>-->

    <!-- Bootstrap CSS -->    
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <!-- bootstrap theme -->
    <link href="/static/css/bootstrap-theme.css" rel="stylesheet">
    <!--external css-->
    <!-- font icon -->
    <link href="/static/css/elegant-icons-style.css" rel="stylesheet" />
    <link href="/static/css/font-awesome.min.css" rel="stylesheet" />


    <link href="/static/css/style.css" rel="stylesheet">
    <link href="/static/css/style-responsive.css" rel="stylesheet" />

	<link href="/static/css/jquery-ui-1.10.4.min.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 -->


  </head>

  <body>
  <!-- container section start -->
  <section id="container" class="">
     
      
      <header class="header dark-bg">
            <div class="toggle-nav">
                <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom"></div>
            </div>

            <!--logo start-->
            <a href="/index" class="logo">校园反电信诈骗 <span class="lite">兼宣传系统</span></a>
            <!--logo end-->



            <div class="top-nav notification-row">                
                <!-- notificatoin dropdown start-->
                <ul class="nav pull-right top-menu">
                    <!-- user login dropdown start-->
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="profile-ava">
                                <img alt="" src="/static/img/avatar1_small.jpg">
                            </span>
                            <span class="username">{{ request.user.username }}</span>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu extended logout">
                            <div class="log-arrow-up"></div>
                        </ul>
                    </li>
                    <!-- user login dropdown end -->
                </ul>
                <!-- notificatoin dropdown end-->
            </div>
      </header>      
      <!--header end-->

      <!--sidebar start-->
      <aside>
          <div id="sidebar"  class="nav-collapse ">
              <!-- sidebar menu start-->
              <ul class="sidebar-menu">                
                  <li class="active">
                      <a class="" href="{% url 'web:index' %}">
                          <i class="icon_house_alt"></i>
                          <span>主页</span>
                      </a>
                  </li>
				  <li class="sub-menu">
                      <a href="{% url 'web:huizong' %}" class="">
                          <i class="icon_document_alt"></i>
                          <span>短信分析</span>
                      </a>
                  </li>
                  <li class="sub-menu">
                      <a href="{% url 'web:yuce' %}" class="">
                          <i class="icon_desktop"></i>
                          <span>分析</span>
                      </a>
                  </li>
                  <li class="sub-menu">
                      <a  href="/admin" class="">
                          <i class="icon_desktop"></i>
                          <span>信息管理</span>
                      </a>
                  </li>
                  
              </ul>
              <!-- sidebar menu end-->
          </div>
      </aside>
      <!--sidebar end-->
      
      <!--main content start-->
      <section id="main-content">
          {% block content %} {% endblock %}
      </section>
      <!--main content end-->
  </section>
  <!-- container section start -->


    <script src="/static/js/bootstrap.min.js"></script>
	<script src="/static/js/jquery.autosize.min.js"></script>
	<script src="/static/js/jquery.placeholder.min.js"></script>

   {% block script %} {% endblock %}

  </body>
</html>

web/templates/SPAM/fenxi.html
{% extends 'SPAM/base.html' %}
{% block title %}分析模块{% endblock %}
{% block content %}
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/echarts@5/dist/echarts.min.js"></script>
<section class="wrapper">
		<div class="row">
				<div class="col-lg-12">
					<h3 class="page-header"><i class="icon_piechart"></i> 分析</h3>
					<ol class="breadcrumb">
						<li><i class="fa fa-home"></i><a href="{% url 'web:index' %}">Home</a></li>
						<li><i class="icon_piechart"></i>分析</li>
						
					</ol>
				</div>
			</div>
            <div class="row">
              <!-- chart morris start -->
              <div class="col-lg-12">
                  <section class="panel">
                      <header class="panel-heading">
                          <h3>可视化图表</h3>
                      </header>
                      <div class="panel-body">
                          <div class="tab-pane" id="chartjs">
                              <div class="row">
                                  <!-- Line -->
                                  <div class="col-lg-12">
                                      <section class="panel">
                                          <header class="panel-heading">
                                              Line
                                          </header>
                                          <div class="panel-body" id="app1" style="height:335px;width:100%">
                                          </div>
                                      </section>
                                  </div>
                              </div>
                              <div class="row">
                                  <!-- Radar -->
                                  <div class="col-lg-6">
                                      <section class="panel">
                                          <header class="panel-heading">
                                              Bar
                                          </header>
                                          <div class="panel-body" id="app2" style="height:335px;width:100%">
                                          </div>
                                      </section>
                                  </div>
                                  <!-- Polar Area -->
                                  <div class="col-lg-6">
                                      <section class="panel">
                                          <header class="panel-heading">
                                              Pie
                                          </header>
                                          <div class="panel-body" id="app3" style="height:335px;width:100%">
                                          </div>
                                      </section>
                                  </div>
                              </div>

                          </div>
                      </div>




                  </section>
              </div>
            </div>
</section>

{% endblock %}
{% block script %}
<script>
var dom = document.getElementById("app1");
var myChart = echarts.init(dom);
var option = {
    title: {
        text: '票房折线图',
    },
    tooltip: {
        trigger: 'axis',
        axisPointer: {            // 坐标轴指示器，坐标轴触发有效
            type: 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
        }
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis: [
        {
            type: 'category',
            data: {{count_name | safe}},
            axisTick: {
                alignWithLabel: true
            }
        }
    ],
    yAxis: [
        {
            type: 'value'
        }
    ],
    series: [
        {
            name: '票房',
            type: 'line',
            barWidth: '60%',
            data: {{count_piaofang | safe}}
        }
    ]
};

if (option && typeof option === 'object') {
    myChart.setOption(option);
}
</script>

<script>
var dom = document.getElementById("app2");
var myChart = echarts.init(dom);
var option = {
    title: {
        text: '前十票房电影',
    },
    tooltip: {
        trigger: 'axis',
        axisPointer: {            // 坐标轴指示器，坐标轴触发有效
            type: 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
        }
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis: [
        {
            type: 'category',
            data: {{zuijia_name | safe}},
            axisTick: {
                alignWithLabel: true
            }
        }
    ],
    yAxis: [
        {
            type: 'value'
        }
    ],
    series: [
        {
            name: '票房',
            type: 'bar',
            barWidth: '60%',
            data: {{zuijia_piaofang | safe}}
        }
    ]
};

if (option && typeof option === 'object') {
    myChart.setOption(option);
}
</script>

<script>
var dom = document.getElementById("app3");
var myChart = echarts.init(dom);
var option = {
    title: {
        text: '各票房电影占比',
    },
       tooltip: {
        trigger: 'item'
    },
    legend: {
        top: '5%',
        left: 'center'
    },
    series: [
        {
            name: '数',
            type: 'pie',
            radius: ['40%', '70%'],
            avoidLabelOverlap: false,
            itemStyle: {
                borderRadius: 10,
                borderColor: '#fff',
                borderWidth: 2
            },
            label: {
                show: false,
                position: 'center'
            },
            emphasis: {
                label: {
                    show: true,
                    fontSize: '40',
                    fontWeight: 'bold'
                }
            },
            labelLine: {
                show: false
            },
            data: {{dict_value | safe}}
        }
    ]
};


if (option && typeof option === 'object') {
    myChart.setOption(option);
}
</script>

{% endblock %}

web/templates/SPAM/huizong.html
{% extends 'SPAM/base.html' %}
{% load static %}
{% block title %}主页{% endblock %}
{% block content %}
<section class="wrapper">
		  <div class="row">
				<div class="col-lg-12">
					<h3 class="page-header"><i class="fa fa-table"></i> 短信分析</h3>
					<ol class="breadcrumb">
						<li><i class="fa fa-home"></i><a href="/web/index">Home</a></li>
						<li><i class="fa fa-table"></i>短信分析</li>
					</ol>
				</div>
			</div>
              <div class="row">
                  <div class="col-sm-12">
                      <section class="panel">
                                       <form class="navbar-form" method="POST" action="/huizong">
                                        {% csrf_token %}
                                            <input style="width: 600px" class="form-control" placeholder="Search" type="text" value="{{ Search }}" name="Search">
                                            <button class="btn btn-info">分析</button>
                                        </form>
                                {{result}}
                      </section>
                  </div>
              </div>
              <!-- page end-->
          </section>




<script src="https://cdn.staticfile.org/jquery/1.10.2/jquery.min.js"></script>




{% endblock %}

web/templates/SPAM/table.html
{% extends 'SPAM/base.html' %}
{% block title %}主页{% endblock %}
{% block content %}
<section class="wrapper">
		  <div class="row">
				<div class="col-lg-12">
					<h3 class="page-header"><i class="fa fa-table"></i> 数据查看</h3>
					<ol class="breadcrumb">
						<li><i class="fa fa-home"></i><a href="/web/index">Home</a></li>
						<li><i class="fa fa-table"></i>数据查看</li>
					</ol>
				</div>
			</div>
              <div class="row">
                  <div class="col-sm-12">
                      <section class="panel">
                          <br/>
                                <ul class="nav top-menu">
                                    <li>
                                        <form class="navbar-form" method="get" action="">
                                            <input class="form-control" placeholder="Search" type="text" value="{{ Search }}" name="Search">
                                            <button class="btn btn-info">搜索</button>
                                        </form>
                                    </li>
                                </ul>

                          <table class="table table-hover" id="divtable">
                              <thead>
                              <tr class="cen">
                                  <th>id</th>
                                  <th>内容</th>
                                  <th>标签</th>
                              </tr>
                              </thead>
                              <tbody id="group_one">
                              {% for resu in results %}
                              <tr>
                                  <td >{{ resu.id }}</td>
                                  <td >{{ resu.youjian }}</td>
                                  <td >{{ resu.lable }}</td>
                              </tr>
                              {% endfor %}
                              </tbody>
                          </table>
                          <span id="s"></span>
							<span id="pageindex1"></span>
							<a href="#" onclick="page.firstPage();">首页</a>


							<a href="#" onclick="page.prePage();">上一页</a>

							<a href="#" onclick="page.nextPage();">下一页</a>

							<a href="#" onclick="page.lastPage();">尾页</a>

							<span id="pageindex"></span>

                      </section>
                  </div>
              </div>
              <!-- page end-->
          </section>


<script type="text/javascript">
// JavaScript Document
/**
* js分页类
* @param iAbsolute 每页显示记录数
* @param sTableId 分页表格属性ID值，为String
* @param sTBodyId 分页表格TBODY的属性ID值,为String,此项为要分页的主体内容
*/
function Page(iAbsolute, sTableId, sTBodyId,sPageId) {
    this.absolute = iAbsolute; //每页最大记录数
    this.tableId = sTableId;
    this.tBodyId = sTBodyId;
    this.rowCount = 0; //记录数
    this.pageCount = 0; //页数
    this.pageIndex = 0; //页索引
    this.__oTable__ = null; //表格引用
    this.__oTBody__ = null; //要分页内容
    this.__dataRows__ = 0; //记录行引用
    this.__oldTBody__ = null;
    this.pageId = sPageId;//显示当前页数的span的ID

    this.__init__(); //初始化;

};
/*
初始化
*/
Page.prototype.__init__ = function () {
    this.__oTable__ = document.getElementById(this.tableId); //获取table引用
    this.__oTBody__ = this.__oTable__.tBodies[this.tBodyId]; //获取tBody引用
    this.__pageInnerDiv__ = document.getElementById(this.pageId);
    this.__dataRows__ = this.__oTBody__.rows;
    this.rowCount = this.__dataRows__.length;
    try {
        this.absolute = (this.absolute <= 0) || (this.absolute > this.rowCount) ? this.rowCount : this.absolute;
        this.pageCount = parseInt(this.rowCount % this.absolute == 0
? this.rowCount / this.absolute : this.rowCount / this.absolute + 1);
    } catch (exception) { }

    this.__updateTableRows__();
};
/*
下一页
*/
Page.prototype.nextPage = function () {
    if (this.pageIndex + 1 < this.pageCount) {
        this.pageIndex += 1;
        this.__updateTableRows__();
    }
};
/*
上一页
*/
Page.prototype.prePage = function () {
    if (this.pageIndex >= 1) {
        this.pageIndex -= 1;
        this.__updateTableRows__();
    }
};
/*
首页
*/
Page.prototype.firstPage = function () {
    if (this.pageIndex != 0) {
        this.pageIndex = 0;
        this.__updateTableRows__();
    }
};
/*
尾页
*/
Page.prototype.lastPage = function () {
    if (this.pageIndex + 1 != this.pageCount) {
        this.pageIndex = this.pageCount - 1;
        this.__updateTableRows__();
    }
};
/*
页定位方法
*/
Page.prototype.aimPage = function (iPageIndex) {
    if (iPageIndex > this.pageCount - 1) {
        this.pageIndex = this.pageCount - 1;
    } else if (iPageIndex < 0) {
        this.pageIndex = 0;
    } else {
        this.pageIndex = iPageIndex;
    }
    this.__updateTableRows__();
};
/*
执行分页时，更新显示表格内容
*/
Page.prototype.__updateTableRows__ = function () {
    var iCurrentRowCount = this.absolute * this.pageIndex;
    var iMoreRow = this.absolute + iCurrentRowCount > this.rowCount ? this.absolute + iCurrentRowCount - this.rowCount : 0;
    var tempRows = this.__cloneRows__();
    //alert(tempRows === this.dataRows);
    //alert(this.dataRows.length);
    var removedTBody = this.__oTable__.removeChild(this.__oTBody__);
    var newTBody = document.createElement("TBODY");
    newTBody.setAttribute("id", this.tBodyId);

    for (var i = iCurrentRowCount; i < this.absolute + iCurrentRowCount - iMoreRow; i++) {
        newTBody.appendChild(tempRows[i]);
    }
    this.__oTable__.appendChild(newTBody);
    /*
    this.dataRows为this.oTBody的一个引用，
    移除this.oTBody那么this.dataRows引用将销失,
    code:this.dataRows = tempRows;恢复原始操作行集合.
    */
    this.__dataRows__ = tempRows;
    this.__oTBody__ = newTBody;
    //alert(this.dataRows.length);
    //alert(this.absolute+iCurrentRowCount);
    //alert("tempRows:"+tempRows.length);
    document.getElementById(this.pageId).innerHTML = "当前页：" + (this.pageIndex + 1);
    document.getElementById('pageindex1').innerHTML = "总页数：" + (this.pageCount);
};
/*
克隆原始操作行集合
*/
Page.prototype.__cloneRows__ = function () {
    var tempRows = [];
    for (var i = 0; i < this.__dataRows__.length; i++) {
        /*
        code:this.dataRows[i].cloneNode(param),
        param = 1 or true:复制以指定节点发展出去的所有节点,
        param = 0 or false:只有指定的节点和它的属性被复制.
        */
        tempRows[i] = this.__dataRows__[i].cloneNode(1);
    }
    return tempRows;
};
</script>

<script src="https://cdn.staticfile.org/jquery/1.10.2/jquery.min.js"></script>

<script type="text/javascript">
	 $(document).ready(function() {
		   page = new Page(10, 'divtable', 'group_one', "pageindex");
	 });

</script>


{% endblock %}

web/templates/SPAM/yuce.html
{% extends 'SPAM/base.html' %}
{% block title %}主页{% endblock %}
{% block content %}
<section class="wrapper">
		  <div class="row">

				<div class="col-lg-12">
					<h3 class="page-header"><i class="fa fa-table"></i> 分析</h3>
					<ol class="breadcrumb">
						<li><i class="fa fa-home"></i><a href="/web/index">Home</a></li>
						<li><i class="fa fa-table"></i>分析</li>
					</ol>
				</div>
			</div>
              <div class="row">
                  <div class="col-sm-12">

                      <section class="panel">

                            <h1>词云</h1>
                          <br/>
                          <img src="/static/img/Cloud.jpg" style="height:605px;width:60%">
                           <br/>
                           <h1> 机器学习-决策树</h1>
                          <br/>
                          <img src="/static/img/tree1.png" style="width:1600px">
                           <br/>
                           <h1> 短信类别统计</h1>
                          <br/>
                          <div class="panel-body" id="app3" style="height:335px;width:100%"></div>

                      </section>
                  </div>
              </div>
              <!-- page end-->
          </section>


<script type="text/javascript" src="https://cdn.staticfile.org/echarts/5.3.0/echarts.min.js"></script>

<script src="https://cdn.staticfile.org/jquery/1.10.2/jquery.min.js"></script>
<script>
var dom = document.getElementById("app3");
var myChart = echarts.init(dom);
var option = {
    title: {
        text: '各类型短信占比',
    },
       tooltip: {
        trigger: 'item'
    },
    legend: {
        top: '5%',
        left: 'center'
    },
    series: [
        {
            name: '数',
            type: 'pie',
            radius: ['40%', '70%'],
            avoidLabelOverlap: false,
            itemStyle: {
                borderRadius: 10,
                borderColor: '#fff',
                borderWidth: 2
            },
            label: {
                show: false,
                position: 'center'
            },
            emphasis: {
                label: {
                    show: true,
                    fontSize: '40',
                    fontWeight: 'bold'
                }
            },
            labelLine: {
                show: false
            },
            data: {{dict_value | safe}}
        }
    ]
};


if (option && typeof option === 'object') {
    myChart.setOption(option);
}
</script>



{% endblock %}